# Generated by Django 5.2.3 on 2025-06-10 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Barang',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kdbrg', models.CharField(max_length=8)),
                ('nama', models.CharField(max_length=75)),
                ('stok', models.IntegerField()),
                ('harga', models.BigIntegerField()),
                ('link_gambar', models.CharField(blank=True, max_length=150)),
            ],
        ),
    ]
