# Generated by Django 5.2.4 on 2025-07-04 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profil', '0002_about_jenis_barang_waktu_posting_barang_jenis_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='media/')),
                ('publish_date', models.DateField()),
                ('title', models.CharField(max_length=100)),
                ('desc', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('css_icon', models.CharField(max_length=50)),
                ('title', models.CharField(max_length=20)),
                ('desc', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_years', models.CharField(max_length=4)),
                ('end_years', models.CharField(max_length=4)),
                ('degree', models.CharField(max_length=100)),
                ('university', models.CharField(max_length=100)),
                ('experience', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('css_icon', models.CharField(max_length=50)),
                ('link', models.TextField()),
                ('title', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('progress', models.IntegerField()),
            ],
        ),
        migrations.RenameField(
            model_name='about',
            old_name='judul',
            new_name='address',
        ),
        migrations.RenameField(
            model_name='about',
            old_name='isi',
            new_name='desc',
        ),
        migrations.RemoveField(
            model_name='about',
            name='image',
        ),
        migrations.AddField(
            model_name='about',
            name='date_birth',
            field=models.DateField(default='1999-01-01'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='about',
            name='email',
            field=models.CharField(default='glg@gmail.com', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='about',
            name='name',
            field=models.CharField(default='galang', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='about',
            name='phone',
            field=models.CharField(default=2394209384, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='about',
            name='postal_code',
            field=models.CharField(default=65654, max_length=7),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Barang',
        ),
        migrations.DeleteModel(
            name='Jenis',
        ),
    ]
