# Generated by Django 5.2.4 on 2025-07-04 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profil', '0003_blog_contact_resume_services_skill_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='desc',
            field=models.TextField(),
        ),
    ]
