# Generated by Django 5.2.4 on 2025-07-04 02:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profil', '0004_alter_blog_desc'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Services',
            new_name='Service',
        ),
    ]
